Replace wireframe cube with solid, rotating coloured cube on a green background
disguise-one/RenderStream pull request #21
Opened 2021-09-21 11:30 UTC by josh-disguise

![cubeee](https://user-images.githubusercontent.com/80043790/134162933-3983f568-f349-4d67-a318-0a58da726497.PNG)

Easier to verify for debugging purposes - moves, no black background, can be picked out in a downscaled image.

2021-09-27 08:53 UTC, husberg-disguise requested changes

2021-09-27 08:53 UTC, husberg-disguise commented on src/samples/DX11/DX11.cpp
> +    std::lock_guard<std::mutex> lock(logMutex);
Shouldn't need a mutex, should it?

2021-09-27 08:53 UTC, husberg-disguise commented on src/samples/DX11/DX11.cpp
> +    g_rs_logToD3(msg);
Null-check

2021-09-27 08:53 UTC, husberg-disguise commented on src/samples/DX11/DX11.cpp
> +    int tick = 0;
No instance-local variables. All logic must be deterministic and based off the frame request data

2021-09-27 08:53 UTC, husberg-disguise commented on src/samples/DX11/DX11.cpp
> +void rsLog(const char* msg)
Maybe move to another PR

2021-09-27 08:53 UTC, husberg-disguise commented on src/samples/DX11/DX11.cpp
> +                const float clearColour[4] = { 0.f, 0.2f, 0.f, 0.f };
Not sure about the green tint. May confuse people with alpha/premult alpha blending errors. 

This should be a clear sample of how to do frontplate rendering.

2021-10-13 09:56 UTC, josh-disguise commented
Will fix and resubmit.

2021-10-13 09:56 UTC, closed without merging